### ISSUE TITLE
Create JS file to access Gas Feed API - details in comments

### ISSUE THREAD

**Issue by shawnholcomb** [shawnholcomb/cartender#17]
Mygasfeed.com

Your Api Key: b05o8u8h1e 

Once your app is complete and released you may submit your app to our 3rd party showcase section.
3rd Party Apps 

Please remember we have two different development environments which uses different domains. 

Development
Domain: devapi.mygasfeed.com
Api key: rfej9napna (All developers) 

Production
Domain: api.mygasfeed.com
Api key: b05o8u8h1e

**Comment by JBDallasTeacher** [comment]
Sorry it took me a while while I was researching about the access to this API but roughly the file can log out the API info
